package me.codethink.heyoffice.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALARM_DATA_ITEM".
 */
public class AlarmDataItem {

    private Long id;
    private Integer hour;
    private Integer minute;

    public AlarmDataItem() {
    }

    public AlarmDataItem(Long id) {
        this.id = id;
    }

    public AlarmDataItem(Long id, Integer hour, Integer minute) {
        this.id = id;
        this.hour = hour;
        this.minute = minute;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

}
