package me.codethink.heyoffice.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmDataItemDaoConfig;

    private final AlarmDataItemDao alarmDataItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmDataItemDaoConfig = daoConfigMap.get(AlarmDataItemDao.class).clone();
        alarmDataItemDaoConfig.initIdentityScope(type);

        alarmDataItemDao = new AlarmDataItemDao(alarmDataItemDaoConfig, this);

        registerDao(AlarmDataItem.class, alarmDataItemDao);
    }
    
    public void clear() {
        alarmDataItemDaoConfig.getIdentityScope().clear();
    }

    public AlarmDataItemDao getAlarmDataItemDao() {
        return alarmDataItemDao;
    }

}
